---
sysctl_conf_template: sysctl.conf
rc_local_template: rc.local
security_limits_conf: limits.conf
security_nproc_conf: 20-nproc.conf
se_linux_conf: selinux.config

krb5_path: /var/kerberos/krb5kdc
krb5_conf: krb5.conf
kdc_conf: kdc.conf
kadm5_acl: kadm5.acl
kpropd_acl: kpropd.acl

kdc_db_file: '{{ krb5_path }}/principal'
kpropd_file: '{{ krb5_path }}/{{ kpropd_acl }}'

yum_install_packages:
 - nmap-ncat
 - bind-utils
 - MySQL-python
 - bzip2
 - unzip
 - wget
 - rng-tools
 - openssl-devel
 - zlib-devel
 - krb5-devel
 - krb5-workstation
 - krb5-libs
 - krb5-server

yum_remove_packages:
 - mariadb-libs
