---
- name: Install MIT KDC
  hosts: all
  gather_facts: false
  
- name: Deploy KDC Master
  hosts: master01
  gather_facts: false
  tags: [ 'master1' ]
  roles:
    - 'kdc-master'

- name: Deploy KDC Slave
  hosts: master02
  gather_facts: false
  tags: [ 'master2' ]
  roles:
    - 'kdc-slave'

- name: Dump Master DB
  hosts: master01
  gather_facts: false
  tasks:
    - name: Run dump
      shell: "kdb5_util dump /var/kerberos/krb5kdc/slave_datatrans {{ kdc_slave_hostname }}"
    - name: Propagate dump file
      shell: "kprop -f /var/kerberos/krb5kdc/slave_datatrans {{ kdc_slave_hostname }}"

