---
- name: Install MIT KDC
  hosts: all
  gather_facts: true

- name: Deploy KDC Primary
  hosts: master01
  tags: [ 'master1' ]
  roles:
    - 'kdc-master'

- name: Deploy Secondary KDC
  hosts: master02
  tags: [ 'master2' ]
  roles:
    - 'kdc-slave'

- name: Dump Primary KDC DB
  hosts: master01
  tasks:
    - name: Run dump
      shell: "kdb5_util dump /var/kerberos/krb5kdc/slave_datatrans"
    - name: Propagate dump file
      shell: "kprop -f /var/kerberos/krb5kdc/slave_datatrans {{ kdc_slave_hostname }}"
  tags: [ 'kdc-init' ]
  become: true

- name: Enable Secondary KDC (RHEL/CentOS)
  hosts: master02
  tasks:
    - name: systemd start krb5kdc
      systemd:
        name: krb5kdc
        state: started
        enabled: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags: [ 'master2' ]
  become: true

- name: Enable Secondary KDC (Ubuntu)
  hosts: master02
  tasks:
    - name: systemd start krb5kdc
      systemd:
        name: krb5-kdc
        state: started
        enabled: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: [ 'master2' ]
  become: true

- name: Setup KDC Replication
  hosts: master01
  tasks:
    - name: Setup kprop crontab
      shell: 'crontab /root/crontab.txt'
  tags: [ 'master1' ]
  become: true

- name: Configure KDC Renewable Tickets
  hosts: master01
  tasks:
    - name: krbtgt  +allow_renewable
      shell: 'kadmin.local -q "modprinc -maxlife 1days -maxrenewlife 7days +allow_renewable krbtgt/{{ kerberos_realm }}@{{ kerberos_realm }}"'
  tags: [ 'master1' ]
  become: true
