---
# Check state of KDC db
- name: Check for existing KDC db
  stat:
    path: '{{ kdc_db_file }}'
  register: kdcdbstat

- name: Configure the KDC DB
  block:
  - name: Configure the KDC
    shell: '/usr/sbin/kdb5_util create -s -P {{ kdc_db_password }}'
  - name: Create KDC Admin
    shell: 'kadmin.local -q "addprinc -pw {{ kdc_admin_password }} {{ kdc_admin_principal }}"'
  - name: Add Master Host Principal
    shell: 'kadmin.local -q "addprinc -randkey host/{{ kdc_master_hostname }}@{{ kerberos_realm }}"'
  - name: Create Master Keytab
    shell: 'kadmin.local -q "ktadd host/{{ kdc_master_hostname }}@{{ kerberos_realm }}"'
  - name: Add Slave Host Principal
    shell: 'kadmin.local -q "addprinc -randkey host/{{ kdc_slave_hostname }}@{{ kerberos_realm }}"'
  tags: [ kdc-init ]
  when: not kdcdbstat.stat.exists
  become: true

- name: Enable kadmin
  become: true
  systemd:
    name: kadmin
    state: started
    enabled: yes

- name: Enable KDC
  become: true
  systemd:
    name: krb5kdc
    state: started
    enabled: yes

