---
- name: Install KDC Server
  become: true
  yum:
    name: '{{ yum_master_packages }}'
    lock_timeout: 180
    state: present

# Check state of KDC db
- name: Configure the KDC
  become: true
  shell: '/usr/sbin/kdb5_util create -s -P {{ kdc_db_pw }}'

- name: Create KDC Admin
  become: true
  shell: 'kadmin.local addprinc {{ kdc_admin_user }} -P {{ kdc_admin_password }}'

- name: Enable kadmin
  become: true
  systemd:
    name: kadmin
    state: started
    enabled: yes

- name: Enable KDC
  become: true
  systemd:
    name: krb5kdc
    state: started
    enabled: yes

- name: Add Master Host Principal
  become: true
  shell: 'kadmin.local -q "addprinc host/{{ kdc_master_hostname }}@{{ kerberos_realm }}'

- name: Add Slave Host Principal
  become: true
  shell: 'kadmin.local -q "addprinc host/{{ kdc_slave_hostname }}@{{ kerberos_realm }}'