---
- name: Check for existing KDC db
  become: true
  stat:
    path: '{{ kdc_db_file }}'
  register: kdcdbstat

- name: Configure the KDC DB
  block:
  - name: Create the db
    shell: '/usr/sbin/kdb5_util create -s -P {{ kdc_db_password }}'
  - name: Create KDC Admin
    shell: 'kadmin.local -q "addprinc -pw {{ kdc_admin_password }} {{ kdc_admin_principal }}"'
  - name: Add Master Host Principal
    shell: 'kadmin.local -q "addprinc -randkey host/{{ kdc_master_hostname }}@{{ kerberos_realm }}"'
  - name: Create Master Keytab
    shell: 'kadmin.local -q "ktadd host/{{ kdc_master_hostname }}@{{ kerberos_realm }}"'
  - name: Add Slave Host Principal
    shell: 'kadmin.local -q "addprinc -randkey host/{{ kdc_slave_hostname }}@{{ kerberos_realm }}"'
  tags: [ kdc-init ]
  when: not kdcdbstat.stat.exists
  become: true

- name: Copy crontab file
  become: true
  template:
    src: '{{ crontab_file }}'
    dest: "/root/crontab.txt"
    mode: 0644

- name: Enable Services RHEL/CentOS
  block:
  - name: Enable kadmin (rhel/centos)
    systemd:
      name: kadmin
      state: started
      enabled: yes
  - name: Enable KDC
    systemd:
      name: krb5kdc
      state: started
      enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  become: true

- name: Enable Services Debian/Ubuntu
  block:
  - name: Enable kadmin (ubuntu)
    systemd:
      name: krb5-admin-server
      state: started
      enabled: yes
  - name: Enable KDC
    systemd:
      name: krb5-kdc
      state: started
      enabled: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: true
