---
- name: Install KDC Server
  become: true
  yum:
    name: '{{ yum_master_packages }}'
    lock_timeout: 180
    state: present

- name: Configure the KDC
  become: true
  shell: '/usr/sbin/kdb5_util create -s'

- name: Enable kadmin
  become: true
  systemd:
    name: kadmin
    state: started
    enabled: yes

- name: Enable kdc
  become: true
  systemd:
    name: krb5kdc
    state: started
    enabled: yes

