---
# Check state of KDC db
- name: Check for existing KDC db
  stat:
    path: '{{ kdc_db_file }}'
  register: kdcdbstat

- name: Configure the KDC DB
  block:
  - name: Create the temp slave db
    shell: '/usr/sbin/kdb5_util create -s -P {{ kdc_db_password }}'
  - name: Acquire Host Keytab
    shell: "kadmin -p {{ kdc_admin_principal }} -r {{ kerberos_realm }} -w {{ kdc_admin_password }} -q 'ktadd host/{{ kdc_slave_hostname }}@{{ kerberos_realm }}'"
  tags: [ kdc-init ]
  when: not kdcdbstat.stat.exists
  become: true

- name: Configure kpropd.acl
  block:
  - name: Add master to acl
    shell: "echo 'host/{{ kdc_master_hostname }}@{{ kerberos_realm }}' > {{ kpropd_file }}"
  - name: Add slaves to acl
    shell: "echo 'host/{{ kdc_slave_hostname }}@{{ kerberos_realm }}' >> {{ kpropd_file }}"
  tags: [ kdc-init ]
  become: true

- name: Enable kpropd (rhel/centos)
  become: true
  systemd:
    name: kprop
    state: started
    enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Enable kpropd (ubuntu)
  become: true
  systemd:
    name: krb5-kpropd
    state: started
    enabled: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
