---
# Check state of KDC db
- name: Check for existing KDC db
  ansible.builtin.stat:
    path: '{{ kdc_db_file }}'
  register: kdcdbstat

- name: Configure the KDC DB
  become: true
  when: not kdcdbstat.stat.exists
  tags: [kdc-init]
  block:
    - name: Create a temp db
      ansible.builtin.shell: '/usr/sbin/kdb5_util create -s -P {{ kdc_db_password }}'
    - name: Acquire Host Keytab
      ansible.builtin.shell: |
        kadmin -p {{ kdc_admin_principal }} \
        -r {{ kerberos_realm }} \
        -w {{ kdc_admin_password }} \
        -q 'ktadd host/{{ kdc_secondary_hostname }}@{{ kerberos_realm }}'

- name: Configure kpropd.acl
  become: true
  tags: [kdc-init]
  block:
    - name: Add primary KDC to ACL
      ansible.builtin.shell: "echo 'host/{{ kdc_primary_hostname }}@{{ kerberos_realm }}' > {{ kpropd_file }}"
    - name: Add secondary KDC to ACL
      ansible.builtin.shell: "echo 'host/{{ kdc_secondary_hostname }}@{{ kerberos_realm }}' >> {{ kpropd_file }}"

- name: Set /var/lib link (ubuntu)
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: [kdc-init]
  block:
    - name: Clear existing directory
      ansible.builtin.file:
        path: '/var/lib/krb5kdc'
        state: absent
    - name: Create /var/lib symlink
      ansible.builtin.file:
        src: /var/kerberos/krb5kdc
        dest: /var/lib/krb5kdc
        state: link

- name: Configure /etc/default DAEMON_ARGS (ubuntu)
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: [kdc-init]
  ansible.builtin.copy:
    src: "krb5-kpropd"
    dest: "/etc/default/krb5-kpropd"
    mode: '0644'

- name: Enable kpropd (rhel/centos)
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags: [kdc-init]
  ansible.builtin.systemd:
    name: kprop
    state: restarted
    daemon_reload: true
    enabled: true

- name: Enable kpropd (ubuntu)
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: [kdc-init]
  ansible.builtin.systemd:
    name: krb5-kpropd
    state: restarted
    daemon_reload: true
    enabled: true
