- name: Install KDC Server
  become: true
  yum:
    name: '{{ yum_master_packages }}'
    lock_timeout: 180
    state: present

# Check state of KDC db
- name: Check for existing KDC db
  stat:
    path: '{{ kdc_db_file }}'
  register: kdcdbstat

- name: Configure the KDC DB
  block:
  - name: Configure the KDC
    shell: '/usr/sbin/kdb5_util create -s -P {{ kdc_db_pw }}'
  - name: Acquire Host Keytab
    shell: "kadmin -p {{ kdc_admin_principal }} -r {{ kerberos_realm }} -P {{ kdc_admin_password }} -q 'ktadd host/{{ kdc_slave_hostname }}@{{ kerberos_realm }}'"
  tags: [ kdc-init ]
  when: not kdcdbstat.exists
  become: true

- name: Enable kpropd
  become: true
  systemd:
    name: kprop
    state: started
    enabled: yes
