---
- name: Check for an existing KDC DB
  become: true
  stat:
    path: '{{ kdc_db_file }}'
  register: kdcdbstat

- name: Configure the KDC DB
  block:
  - name: Create the db
    shell: '/usr/sbin/kdb5_util create -s -P {{ kdc_db_password }}'
  - name: Create KDC Admin
    shell: 'kadmin.local -q "addprinc -pw {{ kdc_admin_password }} {{ kdc_admin_principal }}"'
  - name: Add Primary Host Principal
    shell: 'kadmin.local -q "addprinc -randkey host/{{ kdc_primary_hostname }}@{{ kerberos_realm }}"'
  - name: Create Primary Host Keytab
    shell: 'kadmin.local -q "ktadd host/{{ kdc_primary_hostname }}@{{ kerberos_realm }}"'
  - name: Add Secondary Host Principal
    shell: 'kadmin.local -q "addprinc -randkey host/{{ kdc_secondary_hostname }}@{{ kerberos_realm }}"'
  tags: [ kdc-init ]
  when: not kdcdbstat.stat.exists
  become: true

- name: Copy crontab file
  become: true
  template:
    src: '{{ crontab_file }}'
    dest: "/root/crontab.txt"
    mode: 0644

- name: Enable Services (RHEL/CentOS)
  block:
  - name: Enable kadmin  (rhel)
    systemd:
      name: kadmin
      state: restarted
      daemon_reload: yes
      enabled: yes
  - name: Enable KDC (krb5kdc)
    systemd:
      name: krb5kdc
      state: restarted
      enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  become: true

- name: Enable Services (Debian/Ubuntu)
  block:
  - name: Enable kadmin (krb5-admin-server)
    systemd:
      name: krb5-admin-server
      state: restarted
      daemon_reload: yes
      enabled: yes
  - name: Enable KDC (krb5-kdc)
    systemd:
      name: krb5-kdc
      state: restarted
      enabled: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: true
