---
# Tasks common to both Master and Slave KDC's
- name: Install Master Packages
  become: true
  yum:
    name: '{{ yum_master_packages }}'
    lock_timeout: 180
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Master Packages
  become: true
  apt:
    name: '{{ apt_master_packages }}'
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Copy kdc.conf
  become: true
  template:
    src: '{{ kdc_conf }}'
    dest: "/var/kerberos/krb5kdc/kdc.conf"
    mode: 0600

- name: Copy kadm5.acl
  become: true
  template:
    src: '{{ kadm5_acl }}'
    dest: "/var/kerberos/krb5kdc/kadm5.acl"
    mode: 0600

- name: PermitRootLogin prohibit-password
  become: true
  shell: >
    sed -E -i 's/(^PermitRootLogin ).*/\1prohibit-password/' /etc/ssh/sshd_config
  notify: restart_sshd
