---
- name: Run RHEL/Centos tasks
  block:
  - name: Install Primary KDC Packages (yum)
    yum:
      name: '{{ yum_kdc_packages }}'
      lock_timeout: 180
      state: present
  - name: Copy kdc.conf
    template:
      src: '{{ kdc_conf }}'
      dest: "/var/kerberos/krb5kdc/kdc.conf"
      mode: 0600
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  become: true

- name: Run Debian/Ubuntu tasks
  block:
  - name: Install Primary KDC Packages (apt)
    apt:
      name: '{{ apt_kdc_packages }}'
      state: present
  - name: Create /var/kerberos on Ubuntu
    file:
      path: '{{ krb5_path }}'
      owner: 'root'
      group: 'root'
      mode: 0755
      state: directory
  - name: Create include dir on Ubuntu
    file:
      path: '/etc/krb5.conf.d'
      owner: 'root'
      group: 'root'
      mode: 0755
      state: directory
  - name: Copy kdc.conf (Ubuntu)
    template:
      src: '{{ kdc_conf }}'
      dest: "/etc/krb5kdc/kdc.conf"
      mode: 0600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: true

- name: Copy kadm5.acl
  become: true
  template:
    src: '{{ kadm5_acl }}'
    dest: "/var/kerberos/krb5kdc/kadm5.acl"
    mode: 0600

- name: SSH PermitRootLogin prohibit-password
  become: true
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'
    state: present
    backup: yes
  notify: restart_sshd
