---
# KDC Prerequisites
- name: Remove Packages
  become: true
  yum:
    name: '{{ yum_remove_packages }}'
    state: absent
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Packages (yum)
  become: true
  yum:
    name: '{{ yum_install_packages }}'
    lock_timeout: 180
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Packages (apt)
  become: true
  apt:
    name: '{{ apt_install_packages }}'
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Copy /etc/krb5.conf
  become: true
  template:
    src: '{{ krb5_conf }}'
    dest: "/etc/krb5.conf"
    mode: 0644


- name: Increase Host Entropy
  become: true
  shell: 'rngd -r /dev/urandom'
