---
- name: Configure KDC RHEL/Centos Packages
  block:
  - name: Remove unwanted packages (yum)
    yum:
      name: '{{ yum_remove_packages }}'
      state: absent
  - name: Install Packages (yum)
    yum:
      name: '{{ yum_prereq_packages }}'
      lock_timeout: 180
      state: present
  become: true
  tags: [ kdc-init ]
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Packages (apt)
  become: true
  apt:
    name: '{{ apt_prereq_packages }}'
    state: present
  tags: [ kdc-init ]
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Copy /etc/krb5.conf
  become: true
  template:
    src: '{{ krb5_conf }}'
    dest: "/etc/krb5.conf"
    mode: 0644

- name: Increase Host Entropy
  become: true
  shell: 'rngd -r /dev/urandom'

- name: Adjust Service Files (Ubuntu/Debian)
  block:
  - name: Set krb5-admin-server.service
    replace:
      path: '/etc/systemd/system/multi-user.target.wants/krb5-admin-server.service'
      regexp: '/var/lib/krb5kdc'
      replace: '/var/kerberos/krb5kdc'
  - name:
    replace:
      path: '/etc/systemd/system/multi-user.target.wants/krb5-kdc.service'
      regexp: '/var/lib/krb5kdc'
      replace: '/var/kerberos/krb5kdc'
  - name:
    replace:
      path: '/etc/systemd/system/multi-user.target.wants/krb5-kpropd.service'
      regexp: '/var/lib/krb5kdc'
      replace: '/var/kerberos/krb5kdc'
  become: true
  tags: [ kdc-init ]
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'