---
# KDC Prerequisites
- name: Remove Packages
  become: true
  yum:
    name: '{{ yum_remove_packages }}'
    state: absent

- name: Install Packages
  become: true
  yum:
    name: '{{ yum_install_packages }}'
    lock_timeout: 180
    state: present

- name: Copy /etc/krb5.conf
  become: true
  template:
    src: '{{ krb5_conf }}'
    dest: "/etc/krb5.conf"
    mode: 0644

- name: Copy crontab file
  become: true
  template:
    src: '{{ crontab_file }}'
    dest: "/root/crontab.txt"
    mode: 0644