---
- name: Configure KDC RHEL/Centos Packages
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags: [kdc-init]
  block:
    - name: Remove unwanted packages (yum)
      ansible.builtin.yum:
        name: '{{ prereq_remove_packages_yum }}'
        state: absent
    - name: Install Packages (yum)
      ansible.builtin.yum:
        name: '{{ prereq_packages_yum }}'
        lock_timeout: 180
        state: present

- name: Install Packages (apt)
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: [kdc-init]
  ansible.builtin.apt:
    name: '{{ prereq_packages_apt }}'
    state: present

- name: Copy /etc/krb5.conf
  become: true
  ansible.builtin.template:
    src: '{{ krb5_conf }}'
    dest: "/etc/krb5.conf"
    mode: '0644'

- name: Increase Host Entropy
  become: true
  ansible.builtin.shell: 'rngd -r /dev/urandom'
