---
krb5_path: /var/kerberos/krb5kdc

kdc_conf: kdc.conf
kadm5_acl: kadm5.acl
kpropd_acl: kpropd.acl

kdc_db_file: '{{ krb5_path }}/principal'
kpropd_file: '{{ krb5_path }}/{{ kpropd_acl }}'

common_kdc_yum:
 - krb5-server
 - logrotate

common_kdc_apt:
 - krb5-kdc
 - krb5-admin-server
 - krb5-kpropd
 - logrotate
